/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChannelInput = IDL.Record({
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'logo' : IDL.Text,
  'name' : IDL.Text,
  'group' : IDL.Text,
  'userAgent' : IDL.Text,
});
export const ChannelId = IDL.Nat;
export const Channel = IDL.Record({
  'id' : ChannelId,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'logo' : IDL.Text,
  'name' : IDL.Text,
  'group' : IDL.Text,
  'userAgent' : IDL.Text,
});
export const ReorderEntry = IDL.Record({ 'id' : ChannelId, 'order' : IDL.Nat });
export const ChannelUpdate = IDL.Record({
  'id' : ChannelId,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'logo' : IDL.Text,
  'name' : IDL.Text,
  'group' : IDL.Text,
  'userAgent' : IDL.Text,
});

export const idlService = IDL.Service({
  'addChannel' : IDL.Func([ChannelInput], [ChannelId], []),
  'clearChannels' : IDL.Func([], [], []),
  'deleteChannel' : IDL.Func([ChannelId], [IDL.Bool], []),
  'getChannel' : IDL.Func([ChannelId], [IDL.Opt(Channel)], ['query']),
  'importChannels' : IDL.Func([IDL.Vec(ChannelInput)], [IDL.Nat], []),
  'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'reorderChannels' : IDL.Func([IDL.Vec(ReorderEntry)], [], []),
  'updateChannel' : IDL.Func([ChannelUpdate], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChannelInput = IDL.Record({
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'logo' : IDL.Text,
    'name' : IDL.Text,
    'group' : IDL.Text,
    'userAgent' : IDL.Text,
  });
  const ChannelId = IDL.Nat;
  const Channel = IDL.Record({
    'id' : ChannelId,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'logo' : IDL.Text,
    'name' : IDL.Text,
    'group' : IDL.Text,
    'userAgent' : IDL.Text,
  });
  const ReorderEntry = IDL.Record({ 'id' : ChannelId, 'order' : IDL.Nat });
  const ChannelUpdate = IDL.Record({
    'id' : ChannelId,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'logo' : IDL.Text,
    'name' : IDL.Text,
    'group' : IDL.Text,
    'userAgent' : IDL.Text,
  });
  
  return IDL.Service({
    'addChannel' : IDL.Func([ChannelInput], [ChannelId], []),
    'clearChannels' : IDL.Func([], [], []),
    'deleteChannel' : IDL.Func([ChannelId], [IDL.Bool], []),
    'getChannel' : IDL.Func([ChannelId], [IDL.Opt(Channel)], ['query']),
    'importChannels' : IDL.Func([IDL.Vec(ChannelInput)], [IDL.Nat], []),
    'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'reorderChannels' : IDL.Func([IDL.Vec(ReorderEntry)], [], []),
    'updateChannel' : IDL.Func([ChannelUpdate], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };