/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Channel {
  'id' : ChannelId,
  'url' : string,
  'order' : bigint,
  'logo' : string,
  'name' : string,
  'group' : string,
  'userAgent' : string,
}
export type ChannelId = bigint;
export interface ChannelInput {
  'url' : string,
  'order' : bigint,
  'logo' : string,
  'name' : string,
  'group' : string,
  'userAgent' : string,
}
export interface ChannelUpdate {
  'id' : ChannelId,
  'url' : string,
  'order' : bigint,
  'logo' : string,
  'name' : string,
  'group' : string,
  'userAgent' : string,
}
export interface ReorderEntry { 'id' : ChannelId, 'order' : bigint }
export interface _SERVICE {
  'addChannel' : ActorMethod<[ChannelInput], ChannelId>,
  'clearChannels' : ActorMethod<[], undefined>,
  'deleteChannel' : ActorMethod<[ChannelId], boolean>,
  'getChannel' : ActorMethod<[ChannelId], [] | [Channel]>,
  'importChannels' : ActorMethod<[Array<ChannelInput>], bigint>,
  'listChannels' : ActorMethod<[], Array<Channel>>,
  'reorderChannels' : ActorMethod<[Array<ReorderEntry>], undefined>,
  'updateChannel' : ActorMethod<[ChannelUpdate], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];