/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReorderEntry {
    id: ChannelId;
    order: bigint;
}
export interface ChannelInput {
    url: string;
    order: bigint;
    logo: string;
    name: string;
    group: string;
    userAgent: string;
}
export type ChannelId = bigint;
export interface Channel {
    id: ChannelId;
    url: string;
    order: bigint;
    logo: string;
    name: string;
    group: string;
    userAgent: string;
}
export interface ChannelUpdate {
    id: ChannelId;
    url: string;
    order: bigint;
    logo: string;
    name: string;
    group: string;
    userAgent: string;
}
export interface backendInterface {
    addChannel(input: ChannelInput): Promise<ChannelId>;
    clearChannels(): Promise<void>;
    deleteChannel(id: ChannelId): Promise<boolean>;
    getChannel(id: ChannelId): Promise<Channel | null>;
    importChannels(inputs: Array<ChannelInput>): Promise<bigint>;
    listChannels(): Promise<Array<Channel>>;
    reorderChannels(entries: Array<ReorderEntry>): Promise<void>;
    updateChannel(update: ChannelUpdate): Promise<boolean>;
}
import type { Channel as _Channel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addChannel(arg0: ChannelInput): Promise<ChannelId> {
        if (this.processError) {
            try {
                const result = await this.actor.addChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChannel(arg0);
            return result;
        }
    }
    async clearChannels(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChannels();
            return result;
        }
    }
    async deleteChannel(arg0: ChannelId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannel(arg0);
            return result;
        }
    }
    async getChannel(arg0: ChannelId): Promise<Channel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannel(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannel(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async importChannels(arg0: Array<ChannelInput>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.importChannels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importChannels(arg0);
            return result;
        }
    }
    async listChannels(): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChannels();
            return result;
        }
    }
    async reorderChannels(arg0: Array<ReorderEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderChannels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderChannels(arg0);
            return result;
        }
    }
    async updateChannel(arg0: ChannelUpdate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChannel(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Channel]): Channel | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
